#!/usr/bin/env bash
set -e
if [[ -z "${2}" ]]; then
  echo "Usage: $0 <dns host> <query name>"
  echo "Example: $0 10.250.36.2 www.example.com"
  exit 1
fi
dns_host=$1
query_name=$2

if [[ -z $(dig +short @${dns_host} ${query_name}) ]]; then
  echo 1
  exit 1
else
  echo 0
  exit 0
fi
