#!/usr/bin/env python3
"""Checks for time drift in seconds from control host
author: jeremybusk@gmail.com
# Install
pip3 install ntplib

# Other options for script
from time import ctime
print(ctime(response.tx_time))
"""
import sys

import ntplib

if len(sys.argv) < 4:
    print(f"Usage: {sys.argv[0]} <control ntp host> <tolerable drift in seconds> <host list>")
    print(f"Example: {sys.argv[0]} pool.ntp.org 5 10.250.3.45,10.250.34.150,10.250.170.23,10.250.170.24,10.250.5.2")
    sys.exit()

control_host = sys.argv[1]
allowed_drift_seconds = float(sys.argv[2])
hosts = sys.argv[3].split(',')
c = ntplib.NTPClient()
ntp_control = c.request(control_host)
for host in hosts:
    response = c.request(host)
    delta_time = abs(ntp_control.tx_time - response.tx_time)
    if delta_time > allowed_drift_seconds:
        print(1)
        sys.exit(1)
