#!/usr/bin/env python3
# Mangement url of this api and keys at https://dashboard.nexmo.com/
import os
from pprint import pprint
import sys

import vonage


def main():
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <phone_to> <subject> <text>")
        print(f'Example: {sys.argv[0]} 1801xxxyyyy "Yo Test" "This is a test"')
        sys.exit()
    phone_to = sys.argv[1]
    subject = sys.argv[2]
    phone_text = sys.argv[3]
    phone_text = subject + phone_text
    private_key = os.getenv('NEXMO_SECRET_PEM')
    application_id = os.getenv('NEXMO_APPLICATION_ID')
    phone_from = os.getenv('NEXMO_PHONE_FROM')

    call(phone_from, phone_to, phone_text, application_id, private_key)


def call(phone_from, phone_to, phone_text, application_id, private_key):

    client = vonage.Client(
        application_id=application_id,
        private_key=private_key,
    )
    voice = vonage.Voice(client)
    ncco = [
        {
            'action': 'talk',
            'voiceName': 'Kendra',
            'text': phone_text
        }
    ]

    response = voice.create_call({
        'to': [{
            'type': 'phone',
            'number': phone_to
        }],
        'from': {
            'type': 'phone',
            'number': phone_from
        },
        'ncco': ncco
    })

    pprint(response)


if __name__ == "__main__":
    main()
