name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: [ubuntu-20.04] 
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Run ci-main.sh 
        shell: bash
        run: ./ci-main.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
